services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - frontend/.env
    environment:
      # Override to hit backend service inside compose network
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"
