services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://etosema.ru
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
