import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { CaseBlockMediaWhereInputObjectSchema as CaseBlockMediaWhereInputObjectSchema } from './objects/CaseBlockMediaWhereInput.schema';
import { CaseBlockMediaOrderByWithAggregationInputObjectSchema as CaseBlockMediaOrderByWithAggregationInputObjectSchema } from './objects/CaseBlockMediaOrderByWithAggregationInput.schema';
import { CaseBlockMediaScalarWhereWithAggregatesInputObjectSchema as CaseBlockMediaScalarWhereWithAggregatesInputObjectSchema } from './objects/CaseBlockMediaScalarWhereWithAggregatesInput.schema';
import { CaseBlockMediaScalarFieldEnumSchema } from './enums/CaseBlockMediaScalarFieldEnum.schema';
import { CaseBlockMediaCountAggregateInputObjectSchema as CaseBlockMediaCountAggregateInputObjectSchema } from './objects/CaseBlockMediaCountAggregateInput.schema';
import { CaseBlockMediaMinAggregateInputObjectSchema as CaseBlockMediaMinAggregateInputObjectSchema } from './objects/CaseBlockMediaMinAggregateInput.schema';
import { CaseBlockMediaMaxAggregateInputObjectSchema as CaseBlockMediaMaxAggregateInputObjectSchema } from './objects/CaseBlockMediaMaxAggregateInput.schema';
import { CaseBlockMediaAvgAggregateInputObjectSchema as CaseBlockMediaAvgAggregateInputObjectSchema } from './objects/CaseBlockMediaAvgAggregateInput.schema';
import { CaseBlockMediaSumAggregateInputObjectSchema as CaseBlockMediaSumAggregateInputObjectSchema } from './objects/CaseBlockMediaSumAggregateInput.schema';

export const CaseBlockMediaGroupBySchema: z.ZodType<Prisma.CaseBlockMediaGroupByArgs> = z.object({ where: CaseBlockMediaWhereInputObjectSchema.optional(), orderBy: z.union([CaseBlockMediaOrderByWithAggregationInputObjectSchema, CaseBlockMediaOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CaseBlockMediaScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CaseBlockMediaScalarFieldEnumSchema), _count: z.union([ z.literal(true), CaseBlockMediaCountAggregateInputObjectSchema ]).optional(), _min: CaseBlockMediaMinAggregateInputObjectSchema.optional(), _max: CaseBlockMediaMaxAggregateInputObjectSchema.optional(), _avg: CaseBlockMediaAvgAggregateInputObjectSchema.optional(), _sum: CaseBlockMediaSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CaseBlockMediaGroupByArgs>;

export const CaseBlockMediaGroupByZodSchema = z.object({ where: CaseBlockMediaWhereInputObjectSchema.optional(), orderBy: z.union([CaseBlockMediaOrderByWithAggregationInputObjectSchema, CaseBlockMediaOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CaseBlockMediaScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CaseBlockMediaScalarFieldEnumSchema), _count: z.union([ z.literal(true), CaseBlockMediaCountAggregateInputObjectSchema ]).optional(), _min: CaseBlockMediaMinAggregateInputObjectSchema.optional(), _max: CaseBlockMediaMaxAggregateInputObjectSchema.optional(), _avg: CaseBlockMediaAvgAggregateInputObjectSchema.optional(), _sum: CaseBlockMediaSumAggregateInputObjectSchema.optional() }).strict();